# .gitlab-ci.yml
stages:
  - build
  - deploy

# Build the Next.js application
build:
  stage: build
  image: node:18 # Use a Node.js image
  script:
    - npm install
    - npm run build
    - npm run export # Export static files to the 'out' folder
  artifacts:
    paths:
      - out # Save the build output
    expire_in: 1 week
  only:
    - dev

# Deploy to GitLab Pages
pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r out/. public # Move the exported files to the public folder
  artifacts:
    paths:
      - public # GitLab Pages serves the 'public' folder
  only:
    - dev
