name: Deploy to GitHub Pages

on:
  push:
    branches:
<<<<<<< HEAD
      - dev
=======
      - dev  # Triggers deployment on pushes to the 'dev' branch
>>>>>>> dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
<<<<<<< HEAD
        node-version: '20'
=======
        node-version: '18'  # Ensure compatibility with your Node.js version
>>>>>>> dev

    - name: Install dependencies
      run: npm install

    - name: Build the Next.js app
<<<<<<< HEAD
      run: npm run build  # Only runs build, relying on output: 'export'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./out  # Ensure it matches the output folder
=======
      env:
        NEXT_PUBLIC_BASE_PATH: "/your-repo-name"  # Set your GitHub Pages base path
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # Update if your build output differs
>>>>>>> dev
