name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev  # Trigger deployment on the 'dev' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the Next.js app
      env:
        NEXT_PUBLIC_BASE_PATH: "/body-bell-records"  # Set to your GitHub Pages base path
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}  # Use PAT instead of GITHUB_TOKEN
        publish_dir: ./out
        cname: ''  # Optional: Set your custom domain if needed
