name: OpenTofu Workflow

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'
      - 'backend.tf'
      - 'provider.tf'
  push:
    branches:
      - main
      - dev

jobs:
  opentofu:
    name: OpenTofu Workflow
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up OpenTofu
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.8.7 # Specify version or use "latest"

    # Determine the Environment
    - name: Set Environment
      id: env
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "env=prod" >> $GITHUB_ENV
        else
          echo "env=dev" >> $GITHUB_ENV
        fi

    # Initialize OpenTofu
    - name: OpenTofu Init
      run: |
        tofu init

    # Plan Changes
    - name: OpenTofu Plan
      run: tofu plan

  apply:
    name: OpenTofu Apply
    needs: opentofu
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up OpenTofu
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.8.7 # Specify version or use "latest"

    # Apply Changes
    - name: OpenTofu Apply
      run: tofu apply -auto-approve -var="environment=prod"
